### ISSUE TITLE
Different colors for the tracks with multiple entries

### ISSUE THREAD

**Issue by Ezelty** [lordi/tickmate#79]
The colors introduced in the last release are a great feature! I wonder if it would be possible to add another feature: for each track with multiple entries per day, set different colors that depend on the number of entries for each day and each track. For example, for a track you can chose to have two different colors: blue from 1 to 10 and red for 11 and beyond; for another track, you choose to have red for 1, orange for 2, yellow for 3 and green beyond.
It would be useful for the things you want to do more or less than a certain number of times each day. The different colors would show better if you have reached your goal, when just a tick doesn't mean you've reached it.

**Comment by lordi** [comment]
Hi, thanks for the idea, but I think this might just be too confusing. The current approach is that there is a color per track, so that color can also be used in graphs etc. Later I plan to have graphs with multiple tracks, so these colors are important there as well. I think allowing multiple colors per track would be too much, maybe one can achieve the same effect with different shades of a single color.

**Comment by lordi** [comment]
Sorry, I will close this as I'm currently not planning to implement this.
But thanks for your posting your idea!

**Comment by Ezelty** [comment]
No problem, I understand. Thanks anyway!
